### ISSUE TITLE
Possible to add status on remote

### ISSUE THREAD

**Issue by steinis123** [hobbyquaker/lgtv2mqtt#3]
Is it possible to add a future to se what button i press on the remote control to the tv?
My idea is that I can use the green, red... button to adusjt the light in the living room or If I press pause the light is brighten. 

Thanks

**Comment by hobbyquaker** [comment]
I fear getting button presses is not possible. I do this via InfraRed (https://github.com/hobbyquaker/lirc2mqtt). 
Regarding Playback state, afaik media.controls isn't subscribeable, but I will test this.

**Comment by steinis123** [comment]
ahh ok, I was a afraid of that. Thanks for quick replay btw!
