### ISSUE TITLE
feature request - port number for mqtt broker

### ISSUE THREAD

**Issue by PianSom** [hobbyquaker/lgtv2mqtt#4]
Hi - thanks for producing this.

It would be helpful to include a "port number" argument in config.js (for those of us who run our mqtt broker on a non-standard port to avoid conflicts :) )

**Comment by hobbyquaker** [comment]
This should be already possible via the MQTT url: `<protocol>://<user>:<pass>@<host>:<port>` where protocol is one of `mqtt`, `mqtts`, `ws`or `wss`. So e.g. for using standard mqtt on Port 2000: `mqtt://host:2000`
