### ISSUE TITLE
Magic remote Infrared command

### ISSUE THREAD

**Issue by MattL0** [hobbyquaker/lgtv2mqtt#5]
Hi ,
thank you for this mqtt code,

I am Having an Issus with set up box . I use The Homeseer program too control My webos tv via MQTT.

Here is a picture of what I am trying to do https://imgur.com/a/2EX3r

So i am trying to open a channel of my setup box  ( here channel 643)

It does work when I press physically a random button on my Magic remote., but it doest not work when i do not press physically a button.

So i would like to know if there is any command that mimic a IR command sent from a remote?
Then i would be able to place that command just before the the 6 4 3 buttons command.

In resume, if in setupbox mode,  the tv do not respond to number sent by ''lgtv/set/button'', if i do not shake my remote , or press a buttons before. If i shake the remote or pres a butons .. the automatisation works... And i would like this to be automated without the need to touch the remote.

Sorry if this is not clear , english is not my first language. 

Thank you, 
matt

**Comment by hobbyquaker** [comment]
I fear that won't work, the magic remote seems to go into some kind of standby mode to save battery life and is - i guess - not able to receive commands then. You could work around that with a separate MQTT-connected Infrared-Transceiver, I'm using a cheap DIY on a RaspberryPi in conjunction with LIRC and lirc2mqtt. Another possibility could be a Harmony Hub or a Broadlink device, for both MQTT interfaces should be available.

**Comment by MattL0** [comment]
Thank you
