### ISSUE TITLE
Monitoring on/off status 

### ISSUE THREAD

**Issue by MattL0** [hobbyquaker/lgtv2mqtt#6]
Hi,

I would like to know if  there is a way to monitor the on/off status of the TV with this MQTT package?

thank you

**Comment by MattL0** [comment]
maybe with the states of the internet connection?  iex: if the tv is disconnected from the internet, the tv is off
if tv is connected , the tv is on

**Comment by hobbyquaker** [comment]
the websocket connection status is published on the topic `lgtv/connected`. If the payload equals `2` the connection is established. Downside: After switching in the TV there is quite long latency, you‘ll have to wait up to 15s until the smart-tv services are started and the websocket is connected. hth.

**Comment by MattL0** [comment]
Thank you so much !! that is perfect

**Comment by MattL0** [comment]
I do not know why, but before, when i put the tv off, i was not able to see the off status in lgtv/status/foregroundApp  ( it was showing the last app on tv when the tv was on)

But now , since i subscribed to lgtv/connected , i can see   a ''off'' satus in lgtv/status/foregroundApp when the tv is off. And it is instant
